# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: "3"
services: 
  mysql:
    image: mysql:5.5
    container_name: docker_mysql1
    ports:
    - 3306:3306
    healthcheck:
      test: "exit 0"
    network_mode: host
    environment:
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: test
    
  mongo:
    image: mongo
    container_name: docker_mongo1
    ports:
    - 27017:27017
    healthcheck:
      test: "exit 0"    
    network_mode: host
    environment:
       MONGO_DATABASE: test
      
  user-authentication:
    image: userauthentication-service
    build: ./UserAuthentication-Service
    restart: always
    network_mode: host
    depends_on:
    - mysql
    ports:
    - 8089:8089
    healthcheck:
      test: "exit 0"
      
  note-service:
    image: noteservice
    build: ./NoteService
    restart: always
    network_mode: host
    depends_on:
    - mongo
    ports:
    - 8082:8082
    healthcheck:
      test: "exit 0"
     
  reminder-service:
    image: reminderservice
    build: ./ReminderService
    restart: always
    network_mode: host
    depends_on:
    - mongo
    ports:
    - 8081:8081
    healthcheck:
      test: "exit 0"
      
  category-service:
    image: categoryservice
    build: ./CategoryService
    restart: always
    network_mode: host
    depends_on:
    - mongo
    ports:
    - 8083:8083
    healthcheck:
      test: "exit 0"
      
  user-service:
    image: userservice
    build: ./UserService
    restart: always
    network_mode: host
    depends_on:
    - mongo
    ports:
    - 8080:8080
    healthcheck:
      test: "exit 0"
      
  angular:
    image: angular_keepnote
    build: ./AngularPart_KeepNote
    network_mode: host
    container_name: angular_docker
    ports:
      - 4200:4200
    healthcheck:
      test: "exit 0"  
            
          
          
    
    
    
    
    
    
    
    
    
    
      
   