spring:
  data:
    mongodb:
#      authentication-database: dbAdmin
      username: root
      password: root
      database: test
      port: 27017
      host: localhost
  application:
    name: user-service
server:
  port: 8080



