spring:
  data:
    mongodb:
 #     authentication-database:
      username: root
      password: root
      database: test
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083
  